#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PHASE_U_HIGH     0b00000011
#define PHASE_U_LOW      0b00000001
#define PHASE_U_FLOAT    0b00000000
#define PHASE_V_HIGH     0b00001100
#define PHASE_V_LOW      0b00000100
#define PHASE_V_FLOAT    0b00000000
#define PHASE_W_HIGH     0b00110000
#define PHASE_W_LOW      0b00010000
#define PHASE_W_FLOAT    0b00000000

#define PHASE_0_ON                (PHASE_U_HIGH | PHASE_V_LOW | PHASE_W_FLOAT)
#define PHASE_1_ON                (PHASE_U_HIGH | PHASE_V_FLOAT | PHASE_W_LOW)
#define PHASE_2_ON                (PHASE_U_FLOAT | PHASE_V_HIGH | PHASE_W_LOW)
#define PHASE_3_ON                (PHASE_U_LOW | PHASE_V_HIGH | PHASE_W_FLOAT)
#define PHASE_4_ON                (PHASE_U_LOW | PHASE_V_FLOAT | PHASE_W_HIGH)
#define PHASE_5_ON                (PHASE_U_FLOAT | PHASE_V_LOW | PHASE_W_HIGH)

#define PHASE_0_OFF				(PHASE_U_LOW | PHASE_V_LOW | PHASE_W_FLOAT)
#define PHASE_1_OFF				(PHASE_U_LOW | PHASE_V_FLOAT | PHASE_W_LOW)
#define PHASE_2_OFF				(PHASE_U_FLOAT | PHASE_V_LOW | PHASE_W_LOW)
#define PHASE_3_OFF				(PHASE_U_LOW | PHASE_V_LOW | PHASE_W_FLOAT)
#define PHASE_4_OFF				(PHASE_U_LOW | PHASE_V_FLOAT | PHASE_W_LOW)
#define PHASE_5_OFF				(PHASE_U_FLOAT | PHASE_V_LOW | PHASE_W_LOW)

#define PHASES_FLOAT			(PHASE_U_FLOAT | PHASE_V_FLOAT | PHASE_W_FLOAT)
#define PHASES_LOW_BREAK		(PHASE_U_LOW | PHASE_V_FLOAT | PHASE_W_LOW)
#define PHASES_HIGH_BREAK		(PHASE_U_HIGH | PHASE_V_HIGH | PHASE_W_HIGH)

#define SENSE_U_MUXPOS         AC_MUXPOS_PIN1_gc	//PortA Pin 1
#define SENSE_V_MUXPOS         AC_MUXPOS_PIN2_gc	//PortA Pin 2
#define SENSE_W_MUXPOS         AC_MUXPOS_PIN3_gc	//PortA Pin 3

#define SENSE_0_FNG_AC_MUXPOS	SENSE_W_MUXPOS
#define SENSE_1_RSG_AC_MUXPOS	SENSE_V_MUXPOS
#define SENSE_2_FNG_AC_MUXPOS	SENSE_U_MUXPOS
#define SENSE_3_RSG_AC_MUXPOS	SENSE_W_MUXPOS
#define SENSE_4_FNG_AC_MUXPOS	SENSE_V_MUXPOS
#define SENSE_5_RSG_AC_MUXPOS	SENSE_U_MUXPOS

#endif